version: '3.9'

services:
    app:
        container_name: server
        build: .
        environment:
            MADDR: memcached
            MPORT: 11211
            JWT_SECRET: 123
            ADMIN_NAME: 123
            ADMIN_PASSWORD: 123
        ports:
            - '3000:3000'
        depends_on:
            - memcached

    memcached:
        container_name: memcached
        image: memcached:latest
        ports:
            - '11211:11211'
        restart: always
